
export const DEFAULT_OUTBOUND_TASK_QUEUE = 'WQXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX';

export const TASK_QUEUE_EVERYONE = 'WQXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX';

const OUTBOUND_TASK_QUEUE_BLOCKLIST = [
  TASK_QUEUE_EVERYONE,
];

export const taskQueueCanHandleOutboundCalls = (queueSid) => !OUTBOUND_TASK_QUEUE_BLOCKLIST.includes(queueSid);
